---
# Domain configurations

- include: ntp.yml
  tags:
    - domain
    - ntp

- include: nss.yml
  tags:
    - domain
    - nss

- include: gui-changes.yml
  tags:
    - domain
    - gui

- include: sslproxy.yml
  tags:
    - domain
    - crt

- include: pkgs.yml
  tags:
    - domain
    - pkgs

- include: pam_base.yml
  tags:
    - domain
    - pam

- include: pam_mount.yml
  tags:
    - domain
    - pam
    - pam_mount

- include: smb_config.yml
  tags:
    - domain
    - smb

- include: domain_join.yml
  tags:
    - domain
    - join
