---
# System base configurations.
# At the end of system configuration, we should have a complete
# Edubuntu system

# Requires fact execpath, already set by prereq role.

- include: apt-sources.yml
  tags:
    - base
    - apt-sources

- include: virtualbox-guest-addons.yml
  tags:
    - base
    - virtualbox-addons

- include: system-update.yml
  tags:
    - base
    - update

- include: desktop-environment.yml
  tags:
    - base
    - de
    - desktop-environment

- include: packages.yml
  tags:
    - base
    - pkgs
    - packages

#- include: audio.yml
#  tags:
#    - base
#    - audio

- include: system.yml
  tags:
    - base
    - edubuntu
